In [3]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\Shakshi\Desktop\retail project portofolio\retail_sales_50k.csv"
)

df.head()

,order_id,order_date,month_num,month_name,quarter,region,store_id,customer_id,category,sub_category,sku,quantity,unit_price,unit_cost,discount_pct,revenue,cogs,profit,payment_method,sales_channel
0,ORD-100001,2023-05-21,5,May,Q2,South,STR-SO-07,CUST-87397,Sports,Cricket,SKU-CRI-001,5,2110.16,1369.17,15,8968.18,6845.85,2122.33,EMI,Online
1,ORD-100002,2023-02-17,2,February,Q1,North,STR-NO-04,CUST-64987,Sports,Cricket,SKU-CRI-001,17,1905.38,1167.13,10,29152.31,19841.21,9311.10,Credit Card,App
2,ORD-100003,2023-05-23,5,May,Q2,East,STR-EA-03,CUST-46421,Clothing,Footwear,SKU-FTW-003,1,4104.32,2687.83,0,4104.32,2687.83,1416.49,Cash,Online
3,ORD-100004,2023-02-22,2,February,Q1,North,STR-NO-08,CUST-15695,Groceries,Snacks,SKU-SNK-002,4,73.59,40.25,0,294.36,161.00,133.36,EMI,Online
4,ORD-100005,2023-07-13,7,July,Q3,East,STR-EA-02,CUST-35203,Sports,Swimming,SKU-SWM-001,10,814.64,630.87,10,7331.76,6308.70,1023.06,Debit Card,App

In [4]:
df.shape

(52000, 20)

In [5]:
df.columns

Index(['order_id', 'order_date', 'month_num', 'month_name', 'quarter',
       'region', 'store_id', 'customer_id', 'category', 'sub_category', 'sku',
       'quantity', 'unit_price', 'unit_cost', 'discount_pct', 'revenue',
       'cogs', 'profit', 'payment_method', 'sales_channel'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52000 entries, 0 to 51999
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        52000 non-null  object
 1   order_date      52000 non-null  object
 2   month_num       52000 non-null  int64
 3   month_name      52000 non-null  object
 4   quarter         52000 non-null  object
 5   region          52000 non-null  object
 6   store_id        52000 non-null  object
 7   customer_id     52000 non-null  object
 8   category        52000 non-null  object
 9   sub_category    52000 non-null  object
 10  sku             52000 non-null  object
 11  quantity        52000 non-null  int64
 12  unit_price      52000 non-null  float64
 13  unit_cost       52000 non-null  float64
 14  discount_pct    52000 non-null  int64
 15  revenue         52000 non-null  float64
 16  cogs            52000 non-null  float64
 17  profit          52000 non-null  float64
 18  payment_method  52000 non-null  object
 19  sales_channel   52000 non-null  object
dtypes: float64(5), int64(3), object(12)
memory usage: 7.9+ MB

In [7]:
df['order_date'] = pd.to_datetime(df['order_date'])

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52000 entries, 0 to 51999
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        52000 non-null  object
 1   order_date      52000 non-null  datetime64[ns]
 2   month_num       52000 non-null  int64
 3   month_name      52000 non-null  object
 4   quarter         52000 non-null  object
 5   region          52000 non-null  object
 6   store_id        52000 non-null  object
 7   customer_id     52000 non-null  object
 8   category        52000 non-null  object
 9   sub_category    52000 non-null  object
 10  sku             52000 non-null  object
 11  quantity        52000 non-null  int64
 12  unit_price      52000 non-null  float64
 13  unit_cost       52000 non-null  float64
 14  discount_pct    52000 non-null  int64
 15  revenue         52000 non-null  float64
 16  cogs            52000 non-null  float64
 17  profit          52000 non-null  float64
 18  payment_method  52000 non-null  object
 19  sales_channel   52000 non-null  object
dtypes: datetime64[ns](1), float64(5), int64(3), object(11)
memory usage: 7.9+ MB

In [9]:
df.describe

<bound method NDFrame.describe of          order_id order_date  month_num month_name quarter   region  \
0      ORD-100001 2023-05-21          5        May      Q2    South
1      ORD-100002 2023-02-17          2   February      Q1    North
2      ORD-100003 2023-05-23          5        May      Q2     East
3      ORD-100004 2023-02-22          2   February      Q1    North
4      ORD-100005 2023-07-13          7       July      Q3     East
...           ...        ...        ...        ...     ...      ...
51995  ORD-151996 2023-06-04          6       June      Q2    South
51996  ORD-151997 2023-06-17          6       June      Q2  Central
51997  ORD-151998 2023-06-13          6       June      Q2    North
51998  ORD-151999 2023-01-01          1    January      Q1    North
51999  ORD-152000 2023-08-19          8     August      Q3    South

        store_id customer_id     category sub_category          sku  quantity  \
0      STR-SO-07  CUST-87397       Sports      Cricket  SKU-CRI-001         5
1      STR-NO-04  CUST-64987       Sports      Cricket  SKU-CRI-001        17
2      STR-EA-03  CUST-46421     Clothing     Footwear  SKU-FTW-003         1
3      STR-NO-08  CUST-15695    Groceries       Snacks  SKU-SNK-002         4
4      STR-EA-02  CUST-35203       Sports     Swimming  SKU-SWM-001        10
...          ...         ...          ...          ...          ...       ...
51995  STR-SO-04  CUST-38823    Furniture     Wardrobe  SKU-WRD-001        11
51996  STR-CE-08  CUST-71019    Groceries      Staples  SKU-STP-001         7
51997  STR-NO-10  CUST-32217    Furniture         Sofa  SKU-SOF-002         6
51998  STR-NO-05  CUST-39097     Clothing  Accessories  SKU-ACC-001        14
51999  STR-SO-02  CUST-13432  Electronics       Laptop  SKU-LAP-001         6

       unit_price  unit_cost  discount_pct    revenue       cogs     profit  \
0         2110.16    1369.17            15    8968.18    6845.85    2122.33
1         1905.38    1167.13            10   29152.31   19841.21    9311.10
2         4104.32    2687.83             0    4104.32    2687.83    1416.49
3           73.59      40.25             0     294.36     161.00     133.36
4          814.64     630.87            10    7331.76    6308.70    1023.06
...           ...        ...           ...        ...        ...        ...
51995    38586.80   18672.64            15  360786.58  205399.04  155387.54
51996      421.41     248.90            10    2654.88    1742.30     912.58
51997    34749.48   20005.57             0  208496.88  120033.42   88463.46
51998     2511.95    1608.71            10   31650.57   22521.94    9128.63
51999    58685.37   42730.22            10  316901.00  256381.32   60519.68

      payment_method sales_channel
0                EMI        Online
1        Credit Card           App
2               Cash        Online
3                EMI        Online
4         Debit Card           App
...              ...           ...
51995            EMI      In-Store
51996            EMI           App
51997            EMI        Online
51998           Cash      In-Store
51999    Credit Card        Online

[52000 rows x 20 columns]>

In [10]:
df.describe(include='all')

,order_id,order_date,month_num,month_name,quarter,region,store_id,customer_id,category,sub_category,sku,quantity,unit_price,unit_cost,discount_pct,revenue,cogs,profit,payment_method,sales_channel
count,52000,52000,52000.000000,52000,52000,52000,52000,52000,52000,52000,52000,52000.000000,52000.000000,52000.000000,52000.000000,5.200000e+04,5.200000e+04,52000.000000,52000,52000
unique,52000,NaN,NaN,12,4,5,50,39437,6,30,69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,3
top,ORD-100001,NaN,NaN,May,Q3,North,STR-NO-06,CUST-79204,Beauty,Personal Care,SKU-WRD-001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,Online
freq,1,NaN,NaN,4477,13117,12983,1348,7,8774,1816,1725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10555,20911
mean,NaN,2023-07-01 21:21:02.769231104,6.521769,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.465365,12992.488801,8384.602377,7.142981,1.262389e+05,8.774047e+04,38498.382494,NaN,NaN
min,NaN,2023-01-01 00:00:00,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,30.090000,13.790000,0.000000,2.742000e+01,1.723000e+01,-216998.200000,NaN,NaN
25%,NaN,2023-04-02 00:00:00,4.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,933.650000,572.702500,0.000000,6.003275e+03,3.974220e+03,1616.207500,NaN,NaN
50%,NaN,2023-07-01 00:00:00,7.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,3160.220000,1967.430000,5.000000,2.763123e+04,1.819383e+04,7677.795000,NaN,NaN
75%,NaN,2023-10-01 00:00:00,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.000000,18534.065000,11497.117500,15.000000,1.191828e+05,8.031012e+04,32331.045000,NaN,NaN
max,NaN,2023-12-31 00:00:00,12.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.000000,79990.290000,75859.260000,20.000000,1.598605e+06,1.513240e+06,868670.600000,NaN,NaN
std,NaN,NaN,3.445301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.761068,19120.448711,12926.019427,7.487461,2.241639e+05,1.617173e+05,77742.979182,NaN,NaN

In [11]:
df.isnull().sum()

order_id          0
order_date        0
month_num         0
month_name        0
quarter           0
region            0
store_id          0
customer_id       0
category          0
sub_category      0
sku               0
quantity          0
unit_price        0
unit_cost         0
discount_pct      0
revenue           0
cogs              0
profit            0
payment_method    0
sales_channel     0
dtype: int64

In [12]:
df[['revenue','profit','quantity','unit_price','unit_cost']].describe()

            revenue         profit      quantity    unit_price     unit_cost
count  5.200000e+04   52000.000000  52000.000000  52000.000000  52000.000000
mean   1.262389e+05   38498.382494     10.465365  12992.488801   8384.602377
std    2.241639e+05   77742.979182      5.761068  19120.448711  12926.019427
min    2.742000e+01 -216998.200000      1.000000     30.090000     13.790000
25%    6.003275e+03    1616.207500      5.000000    933.650000    572.702500
50%    2.763123e+04    7677.795000     10.000000   3160.220000   1967.430000
75%    1.191828e+05   32331.045000     15.000000  18534.065000  11497.117500
max    1.598605e+06  868670.600000     20.000000  79990.290000  75859.260000

In [13]:
df.to_csv("cleaned_retail_sales.csv", index=False)

In [14]:
df.shape

(52000, 20)

In [15]:
df.to_csv(
    r"C:\Users\Shakshi\Desktop\retail project portofolio\cleaned_retail_sales.csv",
    index=False
)

In [16]:
import os

os.path.exists(
    r"C:\Users\Shakshi\Desktop\retail project portofolio\cleaned_retail_sales.csv"
)

True